Update '@chakra-ui/react' import
If missing UnorderedList (or OrderedList), an unhandled runtime error is thrown:
ReferenceError: UnorderedList is not defined